package com.vikings.util;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.vikings.dao.mapper.DataImportMapper;
import com.vikings.domain.Album;
import com.vikings.domain.Artist;
import com.vikings.domain.Song;
import com.vikings.domain.identifier.AlbumIdentifier;
import com.vikings.domain.identifier.ArtistIdentifier;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

/**
 * Imports artist/album/song data from JSONs
 * to the database.
 * 
 * JSONs generated by python script.
 * Put the JSONs in
 * src/main/resources/com/vikings/util
 */
@Controller
public class DataImport {
    
    @Autowired
    DataImportMapper dataImportMapper;
    
    // start app and visit this URL to run the import
    @GetMapping("/util/runDataImport")
    public String runDataImport(Model model) {
        createArtists();
        createAlbums();
        createSongs();
        System.out.println("Done.");
        return "index";
    }
    
    private void createArtists() {
        try {
            File artistFile = new File(getClass().getResource("artists.json").getFile());
            ObjectMapper objectMapper = new ObjectMapper();
            JsonNode root = objectMapper.readTree(artistFile);
            JsonNode artists = root.get("artists");
            for (JsonNode artist : artists) {
                System.out.println("Got artist " + artist.get("name").asText());
                Artist resultArtist = new Artist();
                resultArtist.setId(artist.get("id").asText());
                resultArtist.setBio(artist.get("bio").asText());
                resultArtist.setName(artist.get("name").asText());
                List<String> genres = new ArrayList<String>();
                for (JsonNode genre : artist.get("genres")) {
                    genres.add(genre.asText());
                }
                resultArtist.setGenres(genres);
                
                // artist object complete, send to DB
                dataImportMapper.createArtist(resultArtist);
                dataImportMapper.createArtistGenres(resultArtist);
                
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void createAlbums() {
        try {
            File albumFile = new File(getClass().getResource("albums.json").getFile());
            ObjectMapper objectMapper = new ObjectMapper();
            JsonNode root = objectMapper.readTree(albumFile);
            JsonNode albums = root.get("albums");
            for (JsonNode album : albums) {
                System.out.println("Got album " + album.get("name").asText());
                Album resultAlbum = new Album();
                resultAlbum.setId(album.get("id").asText());
                resultAlbum.setName(album.get("name").asText());
                List<ArtistIdentifier> artists = new ArrayList<ArtistIdentifier>();
                for (JsonNode artist : album.get("artists")) {
                    // build a dummy artist object with the correct id
                    ArtistIdentifier artistIdentifier = new ArtistIdentifier();
                    artistIdentifier.setId(artist.asText());
                    artists.add(artistIdentifier);
                }
                resultAlbum.setArtists(artists);
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date releaseDate = dateFormat.parse(album.get("release_date").asText());
                resultAlbum.setReleaseDate(releaseDate);
                // save the songs for later
                
                // album object complete, send to DB
                dataImportMapper.createAlbum(resultAlbum);
                dataImportMapper.createAlbumArtists(resultAlbum);
                
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void createSongs() {
        try {
            File songFile = new File(getClass().getResource("songs.json").getFile());
            ObjectMapper objectMapper = new ObjectMapper();
            JsonNode root = objectMapper.readTree(songFile);
            JsonNode songs = root.get("songs");
            for (JsonNode song : songs) {
                System.out.println("Got song " + song.get("name").asText());
                Song resultSong = new Song();
                resultSong.setId(song.get("id").asText());
                resultSong.setName(song.get("name").asText());
                resultSong.setDuration(song.get("duration").asInt());
                resultSong.setExplicit(song.get("explicit").asBoolean());
                resultSong.setDiscNumber(song.get("disc_number").asInt());
                resultSong.setTrackNumber(song.get("track_number").asInt());
                resultSong.setLyrics(song.get("lyrics").asText());
                List<ArtistIdentifier> artists = new ArrayList<ArtistIdentifier>();
                for (JsonNode artist : song.get("artists")) {
                    // build a dummy artist object with the correct id
                    ArtistIdentifier artistIdentifier = new ArtistIdentifier();
                    artistIdentifier.setId(artist.asText());
                    artists.add(artistIdentifier);
                }
                resultSong.setArtists(artists);
                // build a dummy album object with the correct id
                AlbumIdentifier albumIdentifier = new AlbumIdentifier();
                albumIdentifier.setId(song.get("album").asText());
                resultSong.setAlbum(albumIdentifier);
                
                // song object complete, send to DB
                dataImportMapper.createSong(resultSong);
                dataImportMapper.createSongAlbum(resultSong);
                dataImportMapper.createSongArtists(resultSong);
                
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        
    }
    
}
